base_images:
  ansible-runner:
    name: ansible-runner
    namespace: openshift
    tag: latest
build_root:
  image_stream_tag:
    name: ansible-runner
    namespace: openshift
    tag: latest
images:
- dockerfile_path: build/Dockerfile
  from: base
  to: ci-artifacts
promotion:
  name: "4.6"
  namespace: psap
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 3Gi
  unit:
    requests:
      cpu: "1"
      memory: 1.5Gi
tag_specification:
  name: "4.6"
  namespace: psap
tests:
- as: gpu-operator-e2e
  steps:
    cluster_profile: aws
    test:
    - as: e2e
      commands: ansible-playbook --version
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 3Gi
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: openshift-psap
  repo: ci-artifacts
